# Generated by Django 5.0.3 on 2024-05-24 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_likes_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='desciption',
            new_name='description',
        ),
    ]
