# Generated by Django 5.0.3 on 2024-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_ignname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='IGNname',
            new_name='username',
        ),
    ]
