# Generated by Django 5.0.3 on 2024-05-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_rename_ignname_artist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
