# Generated by Django 5.0.3 on 2024-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_artist_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
