# Generated by Django 5.0.3 on 2024-05-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_alter_artist_first_name_alter_artist_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
